# Generated by Django 3.2.6 on 2022-02-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Üst Menü',
                'verbose_name_plural': 'Üst Menüler',
                'db_table': 'topMenuModel',
            },
        ),
        migrations.CreateModel(
            name='bottomMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('topMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomMenus', to='Admin.topmenumodel')),
            ],
            options={
                'verbose_name': 'Alt Menü',
                'verbose_name_plural': 'Alt Menüler',
                'db_table': 'bottomMenuModel',
            },
        ),
    ]
