# Generated by Django 3.2.6 on 2022-02-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_bottommenumodel_topmenumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenumodel',
            name='userType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
