# Generated by Django 3.2.6 on 2022-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_topmenumodel_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottommenumodel',
            name='userType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
