# Generated by Django 3.2.6 on 2022-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_bottommenumodel_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottommenumodel',
            name='menuType',
            field=models.CharField(blank=True, default='Alt Menü', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topmenumodel',
            name='menuType',
            field=models.CharField(blank=True, default='Üst Menü', max_length=100, null=True),
        ),
    ]
