# Generated by Django 3.2.6 on 2022-02-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20220208_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenumodel',
            name='menuSira',
            field=models.SmallIntegerField(default=0),
        ),
    ]
