# Generated by Django 3.2.6 on 2022-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_topmenumodel_menusira'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottommenumodel',
            name='menuSira',
            field=models.SmallIntegerField(default=0),
        ),
    ]
