# Generated by Django 3.2.6 on 2021-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='appoitmentDayandTime',
            field=models.DateTimeField(null=True),
        ),
    ]
