# Generated by Django 3.2.6 on 2022-02-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0030_remove_customusermodel_peerid'),
        ('chat', '0009_peerinformations'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoRoom', to='onlinedoctor.appointmentmodel'),
        ),
    ]
