# Generated by Django 3.2.6 on 2022-03-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_room_totaldurationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='totalDurationTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
