# Generated by Django 3.2.6 on 2022-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_room_totaldurationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='totalDurationTime',
            field=models.TimeField(blank=True, default='0000-00-00 00:00:00', null=True),
        ),
    ]
