# Generated by Django 3.2.6 on 2021-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0002_alter_timeschedulemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedulemodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
