# Generated by Django 3.2.6 on 2021-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0004_alter_timeschedulemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedulemodel',
            name='is_paid',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
