# Generated by Django 3.2.6 on 2021-11-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0005_timeschedulemodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedulemodel',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
