# Generated by Django 3.2.6 on 2021-11-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0006_timeschedulemodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedulemodel',
            name='money',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
