# Generated by Django 3.2.6 on 2021-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0007_timeschedulemodel_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexDoktorlarYaziModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İndex Yazısı',
                'verbose_name_plural': 'İndex Yazısı',
                'db_table': 'İndex_Yazisi',
            },
        ),
    ]
