# Generated by Django 3.2.6 on 2021-11-08 19:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0009_auto_20211108_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdoktorlaryazimodel',
            name='yazi',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
