# Generated by Django 3.2.6 on 2021-11-10 19:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0010_alter_indexdoktorlaryazimodel_yazi'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerLogo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('aciklamaYazisi', ckeditor.fields.RichTextField()),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer_Ayari',
                'verbose_name_plural': 'Footer_Ayari',
                'db_table': 'footer',
            },
        ),
        migrations.AlterField(
            model_name='indexdoktorlaryazimodel',
            name='yazi',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
