# Generated by Django 3.2.6 on 2021-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0011_auto_20211110_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermodel',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
