# Generated by Django 3.2.6 on 2021-11-10 19:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0012_auto_20211110_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorFeatureIndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doktor_ozellik_image')),
                ('yazi', ckeditor.fields.RichTextField()),
                ('top_title', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'doctorFeatureIndex_Ayari',
                'verbose_name_plural': 'doctorFeatureIndex_Ayari',
                'db_table': 'doctorFeatureIndex',
            },
        ),
    ]
