# Generated by Django 3.2.6 on 2021-11-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0013_doctorfeatureindexmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='featureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doktor_ozellik_image/feature')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'feature_model',
                'verbose_name_plural': 'feature_model',
                'db_table': 'feature',
            },
        ),
    ]
