# Generated by Django 3.2.6 on 2021-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0014_featuremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='cityName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
