# Generated by Django 3.2.6 on 2021-11-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0015_customusermodel_cityname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='cityName',
            new_name='cityCode',
        ),
    ]
