# Generated by Django 3.2.6 on 2021-12-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0019_timeschedulemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoIs', models.CharField(choices=[('nobody', 'Lütfen kim olduğunuzu belirtiniz'), ('doctorAndMember', 'Ben bir doktorum ve sitenize üyeyim'), ('doctorButNotMember', 'Ben bir doktorum ancak sitenize üye değilim'), ('patient/visitor', 'Hastayım/Ziyaretçiyim'), ('forMedia', 'Medya ve İşbirliği')], default='None', max_length=150)),
                ('fullName', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mesaj', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('okundu_bilgisi', models.CharField(default='okunmadı', max_length=30)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
    ]
