# Generated by Django 3.2.6 on 2021-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0020_iletisimmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimmodel',
            name='whoIs',
            field=models.CharField(choices=[('nobody', 'Lütfen kim olduğunuzu belirtiniz'), ('Ben bir doktorum ve sitenize üyeyim', 'Ben bir doktorum ve sitenize üyeyim'), ('Ben bir doktorum ancak sitenize üye değilim', 'Ben bir doktorum ancak sitenize üye değilim'), ('Hastayım/Ziyaretçiyim', 'Hastayım/Ziyaretçiyim'), ('Medya ve İşbirliği', 'Medya ve İşbirliği')], default='None', max_length=150),
        ),
    ]
