# Generated by Django 3.2.6 on 2021-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0021_alter_iletisimmodel_whois'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='kimlik',
            field=models.FileField(blank=True, null=True, upload_to='doctors_file'),
        ),
    ]
