# Generated by Django 3.2.6 on 2022-01-30 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0023_customusermodel_peerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='country',
            field=models.CharField(blank=True, default='Türkiye', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='custom_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='appointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField()),
                ('day', models.CharField(max_length=250)),
                ('money', models.PositiveSmallIntegerField()),
                ('starting_time', models.CharField(max_length=250)),
                ('finishing_time', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('is_paid', models.CharField(default='no', max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentsOfDoctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentsOfPatient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturalar',
                'db_table': 'appointments',
            },
        ),
    ]
