# Generated by Django 3.2.6 on 2022-01-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0024_auto_20220130_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='is_paid',
        ),
    ]
