# Generated by Django 3.2.6 on 2022-01-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0025_remove_appointmentmodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='status',
        ),
    ]
