# Generated by Django 3.2.6 on 2022-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0026_remove_appointmentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(blank=True, default='confirm', max_length=250, null=True),
        ),
    ]
