# Generated by Django 3.2.6 on 2022-01-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0027_appointmentmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='status',
        ),
    ]
