# Generated by Django 3.2.6 on 2022-01-31 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0028_remove_appointmentmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedAppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField()),
                ('day', models.CharField(max_length=250)),
                ('money', models.PositiveSmallIntegerField()),
                ('starting_time', models.CharField(max_length=250)),
                ('finishing_time', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletedAppointmentsOfDoctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleetdAppointmentsOfPatient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'silinenFatura',
                'verbose_name_plural': 'silinenFaturalar',
                'db_table': 'deletedAppointments',
            },
        ),
    ]
