# Generated by Django 3.2.6 on 2022-02-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0029_deletedappointmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='peerId',
        ),
    ]
