# Generated by Django 3.2.6 on 2022-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0031_iletisimsettingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='meeting_method',
            field=models.CharField(blank=True, default='ourSystem', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deletedappointmentmodel',
            name='meeting_method',
            field=models.CharField(blank=True, default='ourSystem', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timeschedulemodel',
            name='meeting_method',
            field=models.CharField(blank=True, default='ourSystem', max_length=50, null=True),
        ),
    ]
