# Generated by Django 3.2.6 on 2022-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0032_auto_20220226_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='totalDuration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
