# Generated by Django 3.2.6 on 2022-03-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0033_appointmentmodel_totalduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='totalDuration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
